"""Alembic environment — async engine, models discovered via app.persistence.db.Base."""

import asyncio
from logging.config import fileConfig
from typing import Any

from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

import app.persistence.types
from app.core.config import get_settings
from app.persistence import load_models
from app.persistence.db import Base

# Every module under app.persistence, so all tables are on Base.metadata.
# A hand-written import list here silently produces an EMPTY autogenerated
# revision for any model nobody remembered to add.
load_models()

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

config.set_main_option("sqlalchemy.url", get_settings().postgres.async_url)

#: Module holding the project's own column types (`UtcDateTime`, ...).
_TYPES_MODULE = app.persistence.types.__name__


def render_item(item_type: str, obj: Any, autogen_context: AutogenContext) -> bool:
    """Make autogenerate emit an import for our own column types.

    Alembic renders a user-defined type module-qualified
    (`app.persistence.types.UtcDateTime()`) but adds no import for it, so the
    generated revision raises `NameError` the first time it is run. Returning
    False keeps the default rendering; the side effect is the point.
    """
    if item_type == "type" and type(obj).__module__ == _TYPES_MODULE:
        autogen_context.imports.add(f"import {_TYPES_MODULE}")
    return False


def run_migrations_offline() -> None:
    """Run migrations without a DB connection (emits SQL)."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations against the configured database."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
